name: mentora_admin
description: Admin mentora soluções controle de licenças e serviços.
publish_to: 'Mentora Soluções'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_messaging: ^14.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.9

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - lib/assets/

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "lib/assets/icon.png"

flutter_native_splash:
  color: "#92D38C"
  image: lib/assets/splash.png
  android: true
  ios: true
  web: true