// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHcja7dZSBEYdNpZM_4QSOoCfwYq942cc',
    appId: '1:613806457783:web:15c83874560a0b1067de32',
    messagingSenderId: '613806457783',
    projectId: 'mentora-admin-14bf8',
    authDomain: 'mentora-admin-14bf8.firebaseapp.com',
    storageBucket: 'mentora-admin-14bf8.appspot.com',
    measurementId: 'G-W8PYBVW9DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Hvb2LX17m5fwHvPd6U93OeCc9iQzu5A',
    appId: '1:613806457783:android:2d95110d687fa92a67de32',
    messagingSenderId: '613806457783',
    projectId: 'mentora-admin-14bf8',
    storageBucket: 'mentora-admin-14bf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2rQuwg94h43FwGYYYBhuwJ6o36LFl7zc',
    appId: '1:613806457783:ios:8921f013ef843c1767de32',
    messagingSenderId: '613806457783',
    projectId: 'mentora-admin-14bf8',
    storageBucket: 'mentora-admin-14bf8.appspot.com',
    iosBundleId: 'br.com.mentorasolucoes.mentoraAdmin',
  );
}
